apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-writer
  labels:
    app: {{ .Release.Name }}
    component: writer
spec:
  type: ClusterIP # Internal only
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}
    component: writer